force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batches</relationshipLabel>
    <relationshipName>Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Faculity__c.field-meta.xml
<CustomField>
    <fullName>Faculity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faculity</label>
    <referenceTo>Faculity__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faculity__c/Faculity__c.object-meta.xml
<CustomObject>
    <label>Faculity</label>
    <nameField>
        <label>Faculity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <inlineHelpText>Enter Student name here</inlineHelpText>
    <label>Student Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_in_batch__c/Student_in_batch__c.object-meta.xml
<CustomObject>
    <label>Student in batch</label>
    <nameField>
        <label>Student in batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studentes in batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_in_batch__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Studentes in batches</relationshipLabel>
    <relationshipName>Studentes_in_batches</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_in_batch__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Studentes in batches</relationshipLabel>
    <relationshipName>Studentes_in_batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/classTest.cls
public class classTest {
	public static void r1()
    {
        list<Sobject> op2 = [SELECT Id, OpportunityId, ContactId, Opportunity.Account.Name FROM OpportunityContactRole Where Opportunity.name like '%a'];
        system.debug(op2);
        system.debug('-=-=-=-=-===-=-=-=-=-=');
        //SELECT Id, OpportunityId, ContactId FROM OpportunityContactRole
        
        //Id owner = UserInfo.getUserId();
        //list<list<Sobject>> lst = [Find 'Test' IN ALL FIELDS RETURNING Account(id where OwnerID = :UserInfo.getUserId()), Contact, Opportunity(id where CloseDate = THIS_FISCAL_YEAR)];
        //System.debug(lst);
          
        
        //list<String> std = new List<String>{'Mahipal','Harsh','Prem'};
     	//list<Student__c> lst = [select id, Student_Name__c from Student__c where Student_Name__c IN :std AND Registration_Date__c = THIS_FISCAL_QUARTER];
        //System.debug(lst);
        //WHERE Batch__r.Course__r.Name != 'Php'
        
        
//        list<Student_in_batch__c> lstTest = [select Id,Student__r.Name, Batch__r.Course__r.Name , Batch__r.Course__r.Faculity__r.Name from Student_in_batch__c WHERE Student__r.Name LIKE 'Kri%' AND Batch__r.Course__r.Faculity__r.Name LIKE 'Kri%' AND Batch__r.Course__r.Name != 'Php'];
//        list<Student_in_batch__c> lstTest = [select Id,Student__r.Name, Batch__r.Course__r.Name , Batch__r.Course__r.Faculity__r.Name from Student_in_batch__c WHERE Student__r.Name LIKE 'Kri%' AND Batch__r.Course__r.Faculity__r.Name LIKE 'Kri%' AND Batch__r.Course__r.Name != 'Php'];
  //      System.debug(lstTest);
        
        //list<Sobject> lst1 = [select Id,Student__r.Name, Batch__r.Course__r.Name , Batch__r.Course__r.Faculity__r.Name from Student_in_batch__c ];
        //System.debug(lst1);
        
        
        //list<batch__c> lst2 = [select Id,Name, Course__r.Name, Course__r.Faculity__r.Name from Batch__c];
        //System.debug(lst2[0].Course__r.Faculity__r.Name);
        
        System.debug('================================3A==================================');
        List<Account> op = [select id, 
                            (select id from contacts), 
                            (select id from Opportunities where name like '%A') 
                            from Account];		
		for(Account a : op)
        {
            System.debug(a.contacts);
        }
        //System.debug(op);
    }
}