force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batches</relationshipLabel>
    <relationshipName>Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Course_Fee__c.field-meta.xml
<CustomField>
    <fullName>Course_Fee__c</fullName>
    <inlineHelpText>Enter Course Fee</inlineHelpText>
    <label>Course Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <inlineHelpText>Enter Student name here</inlineHelpText>
    <label>Student Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_in_batch__c/Student_in_batch__c.object-meta.xml
<CustomObject>
    <label>Student in batch</label>
    <nameField>
        <label>Student in batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studentes in batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_in_batch__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Studentes in batches</relationshipLabel>
    <relationshipName>Studentes_in_batches</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_in_batch__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Studentes in batches</relationshipLabel>
    <relationshipName>Studentes_in_batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TEST_J.cls
public class TEST_J {
	public static void test(String Course, Integer start_fee, Integer last_fee)
    {
    	list<Student_in_batch__c> lst = [select id,Student__r.Student_Name__c from Student_in_batch__c where Batch__r.Course__r.Name = :Course AND Student__r.Course_Fee__c >= :start_fee AND Student__r.Course_Fee__c <= :last_fee ];
        System.debug(lst);
    }
    public static void MergeTest()
    {
        list<Account> acnt_lis = [select id from account limit 2];
        //System.debug(acnt_lis);
        Savepoint sp1 = Database.setSavepoint();
        merge acnt_lis[1] acnt_lis[0];
        Database.rollback(sp1);
    }
}